Диплом основной функционал
dzverkov/java-explore-with-me pull request #2
Opened 2023-01-09 08:57 UTC by dzverkov

2023-01-11 01:10 UTC, alexache requested changes

2023-01-11 01:10 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/events/service/EventServiceImpl.java
> +        mergedEvent.setInitiator(user);
Мне кажется, не помешает проверять, что это пользователь, который и создавал событие пытается его поменять

2023-01-11 01:10 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/events/service/EventServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Это плохой способ, нужно просто получать это количество участников запросом к базе

2023-01-11 01:10 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/events/service/EventServiceImpl.java
> +        request.setStatus(RequestStatus.REJECTED);
Стоит проверять, создатель ли события пытается сделать эту операцию

2023-01-11 01:10 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/events/service/EventServiceImpl.java
> +
Стоит проверять, создатель ли события пытается сделать эту операцию

2023-01-11 01:10 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/stat/StatClient.java
> +    }
Не хватает чтение статистики из сервиса

2023-01-11 01:10 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/users/service/UserServiceImpl.java
> +        Optional<User> user = userRepository.findUserByName(newUser.getName());
Скорее важнее проверять уникальность не имени, а емейла

2023-01-11 08:25 UTC, dzverkov commented on ewm-service/src/main/java/ru/practicum/server/categories/controller/CategoryController.java
> +    ResponseEntity<Object> getAllCategories(
По поводу ResponseEntity, в данном случае наверно необязательно его использовать, но я основывался на рекомендациях ревьюверов к предидущим проектам, которые ремомендовали использовать ResponseEntity для возможности передачи на клиент дополнительной информации, о статусе запроса например.

2023-01-14 19:34 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/events/service/EventServiceImpl.java
> +    private List<Event> getEventsWithConfirmedRequests(List<Event> events) {
(не замечание) Выглядит отлично!

2023-01-14 19:34 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/events/service/EventServiceImpl.java
> +            return -1L;
(опционально) не очень рекомендуется "прощать" исключения

2023-01-14 19:34 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/server/categories/controller/CategoryController.java
> +    ResponseEntity<Object> getAllCategories(
На будущее советую (навязываюсь с советом) придерживаться принципа KISS -  к чему усложнять, если и простой вариант будет работать

2023-01-14 19:34 UTC, alexache approved these changes

2023-01-14 19:49 UTC, merged